# Generated by Django 6.0.7 on 2026-07-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableFaitAffectationDatalab',
            fields=[
                ('import_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dr', models.CharField(blank=True, max_length=150, null=True)),
                ('delegation', models.CharField(blank=True, max_length=100, null=True)),
                ('num_dossier', models.CharField(blank=True, max_length=50, null=True)),
                ('type_affectation', models.CharField(blank=True, max_length=100, null=True)),
                ('date_ouverture_dossier', models.DateField(blank=True, null=True)),
                ('denomination_projet', models.TextField(blank=True, null=True)),
                ('administration_beneficiaire', models.CharField(blank=True, max_length=200, null=True)),
                ('nature_sommier', models.CharField(blank=True, max_length=100, null=True)),
                ('num_id', models.CharField(blank=True, max_length=50, null=True)),
                ('trn', models.CharField(blank=True, max_length=20, null=True)),
                ('num_trn', models.CharField(blank=True, max_length=50, null=True)),
                ('indice_trn', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_construction', models.CharField(blank=True, max_length=50, null=True)),
                ('nature_construction', models.TextField(blank=True, null=True)),
                ('superficie_concernee', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('montant_affectation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('statut_dossier', models.CharField(blank=True, max_length=100, null=True)),
                ('date_resultat_enquete', models.DateField(blank=True, null=True)),
                ('mobilisable', models.TextField(blank=True, null=True)),
                ('superficie_proposee', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('num_pv_expertise', models.CharField(blank=True, max_length=50, null=True)),
                ('date_expertise', models.DateField(blank=True, null=True)),
                ('montant_expertise', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('date_pcv', models.DateField(blank=True, null=True)),
                ('montant_total_regle', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('num_fiche', models.CharField(blank=True, max_length=50, null=True)),
                ('date_emission_fiche', models.DateField(blank=True, null=True)),
                ('date_virement', models.DateField(blank=True, null=True)),
                ('montant_fiche', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('numero_pv', models.CharField(blank=True, max_length=50, null=True)),
                ('type_pv', models.CharField(blank=True, max_length=100, null=True)),
                ('date_envoi_pva_dr', models.DateField(blank=True, null=True)),
                ('statut_pv', models.CharField(blank=True, max_length=100, null=True)),
                ('constat_realisation', models.TextField(blank=True, null=True)),
                ('date_constat_realisation', models.DateField(blank=True, null=True)),
                ('constat_utilisation', models.TextField(blank=True, null=True)),
                ('objet_utilisation', models.TextField(blank=True, null=True)),
                ('date_constat_utilisation', models.DateField(blank=True, null=True)),
                ('type_desaffectation', models.CharField(blank=True, max_length=100, null=True)),
                ('motif_desaffectation', models.TextField(blank=True, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('motif_cloture', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table_fait_affectation_datalab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdministrationBeneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('nom_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom en arabe')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse_fr', models.TextField(blank=True, null=True, verbose_name='Adresse en français')),
                ('adresse_ar', models.TextField(blank=True, null=True, verbose_name='Adresse en arabe')),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Administration bénéficiaire',
                'verbose_name_plural': 'Administrations bénéficiaires',
                'ordering': ['nom'],
            },
        ),
    ]
