# Generated by Django 6.0.7 on 2026-07-13 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PvAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_import_id', models.PositiveBigIntegerField()),
                ('num_dossier', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_pv', models.CharField(blank=True, max_length=50, null=True)),
                ('administration_source_nom', models.CharField(max_length=200)),
                ('pv_key', models.CharField(max_length=255, unique=True)),
                ('template_name', models.CharField(default='pv_affectation_template.docx', max_length=150)),
                ('generated_docx', models.CharField(blank=True, max_length=500)),
                ('generated_pdf', models.CharField(blank=True, max_length=500)),
                ('pdf_hash_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pv_affectations', to='affectations.administrationbeneficiaire')),
            ],
            options={
                'verbose_name': "PV d'affectation",
                'verbose_name_plural': "PV d'affectation",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pv_otp_codes', to=settings.AUTH_USER_MODEL)),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='affectations.pvaffectation')),
            ],
            options={
                'verbose_name': 'Code OTP PV',
                'verbose_name_plural': 'Codes OTP PV',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureOtpPv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_verified', models.BooleanField(default=True)),
                ('signed_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('pdf_hash_sha256', models.CharField(max_length=64)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pv_signatures', to='affectations.administrationbeneficiaire')),
                ('pv', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signature_proof', to='affectations.pvaffectation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pv_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature OTP PV',
                'verbose_name_plural': 'Signatures OTP PV',
                'ordering': ['-signed_at'],
            },
        ),
    ]
