# Generated by Django 6.0.7 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affectations", "0002_pvaffectation_otpcode_signatureotppv"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpcode",
            name="invalidated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="invalidation_reason",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
