# Generated by Django 6.0.7 on 2026-07-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0005_replace_generated_pv_with_amlacs_pdf_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatureotppv',
            name='pades_certificate_fingerprint_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='signatureotppv',
            name='pades_certificate_serial_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='signatureotppv',
            name='pades_certificate_subject',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signatureotppv',
            name='pades_profile',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='signatureotppv',
            name='pades_signature_field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
