# Generated by Django 6.0.7 on 2026-07-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0006_signatureotppv_pades_certificate_fingerprint_sha256_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('adresse', models.TextField()),
            ],
            options={
                'verbose_name': 'Délégation',
                'verbose_name_plural': 'Délégations',
                'ordering': ['nom'],
            },
        ),
    ]
