# Generated by Django 6.0.7 on 2026-07-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affectations", "0007_delegation"),
    ]

    operations = [
        migrations.AddField(
            model_name="delegation",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
