# Generated by Django 6.0.7 on 2026-07-24 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0008_delegation_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pvaffectation',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pv_affectations', to='affectations.delegation'),
        ),
        migrations.AddField(
            model_name='pvaffectation',
            name='dr_pdf_hash_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pvaffectation',
            name='dr_signed_pdf',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pvaffectation',
            name='is_signed_by_dr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pvaffectation',
            name='signed_by_dr_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DrOtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('invalidation_reason', models.CharField(blank=True, max_length=100)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dr_otp_codes', to='affectations.pvaffectation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dr_pv_otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code OTP PV DR',
                'verbose_name_plural': 'Codes OTP PV DR',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureOtpPvDr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_verified', models.BooleanField(default=True)),
                ('signed_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('pdf_hash_sha256', models.CharField(max_length=64)),
                ('pades_profile', models.CharField(blank=True, max_length=30)),
                ('pades_signature_field', models.CharField(blank=True, max_length=100)),
                ('pades_certificate_subject', models.TextField(blank=True)),
                ('pades_certificate_serial_number', models.CharField(blank=True, max_length=64)),
                ('pades_certificate_fingerprint_sha256', models.CharField(blank=True, max_length=64)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pv_signatures', to='affectations.delegation')),
                ('pv', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dr_signature_proof', to='affectations.pvaffectation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dr_pv_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature OTP PV DR',
                'verbose_name_plural': 'Signatures OTP PV DR',
                'ordering': ['-signed_at'],
            },
        ),
    ]
