# Generated by Django 6.0.7 on 2026-07-24 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('affectations', '0007_delegation'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='affectations.delegation'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('consultation', 'Consultation uniquement'), ('signataire', 'Signataire'), ('admin_organisme', 'Administrateur organisme'), ('admin_dde', 'Administrateur DDE'), ('signataire_delegation', 'Signataire délégation')], default='consultation', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('administration__isnull', True), ('delegation__isnull', False), ('role', 'signataire_delegation')), models.Q(models.Q(('role', 'signataire_delegation'), _negated=True), ('delegation__isnull', True)), _connector='OR'), name='accounts_user_scope_matches_role'),
        ),
    ]
